### ISSUE TITLE
Add support for reiserfs

### ISSUE THREAD

**Issue by hstaudacher** [linux-sunxi/linux-sunxi#198]
the kernel supports many filessytems out of the box. It would be nice if you could add also support for reiserfs.

**Comment by dan-and** [comment]
All patwood kernels had reiserfs support. As well as mine.
What kernel version are you using?

On 16. Juli 2014 10:11:04 MESZ, Holger Staudacher notifications@github.com wrote:

> the kernel supports many filessytems out of the box. It would be nice
> if you could add also support for reiserfs. 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/linux-sunxi/linux-sunxi/issues/198

## 

Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.

**Comment by hstaudacher** [comment]
I'm using a lemaker distribution that ships with 3.4.90. See http://www.lemaker.org/content-9-38-1.html

This is what the distributor says to the topic: http://forum.lemaker.org/viewthread.php?tid=1122&extra=page%3D1

**Comment by romanrm** [comment]
The Linux-sunxi 3.4 kernel source does include support for ReiserFS, and that support can be utilized when compiling the kernel with a .config file including ReiserFS either as a module, or built into the kernel.  Your issue is that some "lemaker distribution", ships a kernel that is not built with ReiserFS support, and the question is, what exactly do you want from the Linux-sunxi project here? Ask your distribution vendor to change their kernel package config in ways you require, or use a different kernel package, or compile a kernel youself. Plenty of options.

**Comment by hstaudacher** [comment]
Alright, thanks.
