### ISSUE TITLE
is it possible to reaktivate the "sunxi_ve_mem_reserve"  option ???

### ISSUE THREAD

**Issue by Moorviper** [linux-sunxi/linux-sunxi#209]
the hardcoded 80MB are bad.
for vdpau and 1080p output more memory is needed and if it were configurable with the uEnv i don't have to recompile the kernel if i want to change the amount of memory 
greeting
daniel

**Comment by oliv3r** [comment]
Iirc we use a dynamic  allocator ...

On September 12, 2014 1:50:09 AM CEST, Moorviper notifications@github.com wrote:

> the hardcoded 80MB are bad.
> for vdpau and 1080p output more memory is needed and if it were
> configurable with the uEnv i don't have to recompile the kernel if i
> want to change the amount of memory 
> greeting
> daniel
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/linux-sunxi/linux-sunxi/issues/209

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by amery** [comment]
I guess he is using a lichee 3.4

**Comment by rellla** [comment]
it's this https://github.com/linux-sunxi/linux-sunxi/blob/sunxi-3.4/drivers/media/video/sunxi/sunxi_cedar.c#L934

**Comment by amery** [comment]
I also thought it was dynamic these days... but it was only to use cma instead of an early reserve...

thanks rellla for clarifying

sunxi_cedarx.mem_size anyone?

**Comment by rellla** [comment]
may it be possible to easily comment this out? 
ve_size has it's value already https://github.com/linux-sunxi/linux-sunxi/blob/sunxi-3.4/arch/arm/plat-sunxi/core.c#L169. why not just skip the reserve_mem i case of CONFIG_CMA? ve_size is the same anyway

**Comment by amery** [comment]
because it's not to be used by plat_sunxi, but by sunxi-cedarx. imagine you want to decide on modprobe time for example.

**Comment by rellla** [comment]
right. missed that.

**Comment by ssvb** [comment]
The point is that it is never nice to make it necessary for the end users to tweak the kernel cmdline just to get their video decoded. The kernel cmdline hack was introduced as a way to reduce memory footprint for the users who care less about the graphics and multimedia. Some users caused troubles for themselves by trying to reduce the sizes of these reservations to something that kinda works, and then suddenly their system failed in an ugly way some day when it was not enough.

With CMA it is possible to make everything work automagically and use as much memory as necessary. We are just not quite there yet.

**Comment by ssvb** [comment]
Just some additional clarifications.

Before CMA, we had a boot time reservation for the cedar memory regardless of whether the cedar was in use or not (the amount of lost memory was configured in the kernel cmdline and could be also set to 0). In order to change the size of this reservation, reboot was necessary.

With the introduction of CMA, the cedar memory is allocated only when the cedar module is loaded. And freed when the cedar module is removed. So a headless system does not need to care about the kernel cmdline anymore and has no memory wasted by default. When a user wants to play some hardware accelerated video, he just loads the cedar module and the memory is allocated at that time. I hardcoded the 80MB size because it was assumed to be the largest buffer size ever required by cedar (because Android also used to do exactly 80MB memory reservation).

This is still not perfect. In fact we can allocate the buffer for cedar only for the period of time when cedar device is really opened and mmapped. And the size of this allocation can be also changed at runtime (naturally, when the cedar device is closed) without any need to reboot the system. Either by introducing a new cedar ioctl or by exposing some sysfs knob.

**Comment by Moorviper** [comment]
Ok thanks for clarifying 
So i modificate the sunxi_cedar.c and only rebuild the module 
jemk tested it with 120MB and 1080i channel worked (i think with 720p output)

i will try it / as i understand i can hardcode 256 MB if i need it ??

**Comment by amery** [comment]
@ssvb so you are vetoing a `max_mem` module parameter? it doesn't feel incompatible with a fully dynamic allocation in future, and saves people from recompiling.
