### ISSUE TITLE
[sunxi-next] mmc driver does not ensure boot device gets mmcblk0

### ISSUE THREAD

**Issue by dllud** [linux-sunxi/linux-sunxi#242]
Old sunxi-mmc driver had boot checks that made sure the boot device always got mmcblk**0** node. New driver doesn't.

Virtually all distro images are configured with rootfs pointing to mmcblk**0**. Thus, without checks, we get kernel panics on boards with two sdcards, just by swapping them.

Notice that current U-Boot still has those checks and makes sure the boot card is always number **0**: [board/sunxi/board.c#L344](https://github.com/RobertCNelson/u-boot/blob/master/board/sunxi/board.c#L344). Also, if I'm not mistaken, on desktops and servers, boot hard drive is always on sd**a** node.

The lack of this feature was found by @zador-blood-stained while [adding support for CB2-2Card in Armbian](https://github.com/igorpecovnik/lib/issues/114). There you can a good sense on why it is needed.

**Comment by jwrdegoede** [comment]
The bootloader swaps the mmc slots so that the env, boot.scr, etc. get tried on the actual boot device first. I see no reason to do similar tricks in the kernel we've had things like root by uuid for ages to solve problems like this. As for your argument that on desktops and servers the boot drive is always sda, no it is not. Sometimes it is even a different drive every other boot. This is exactly what we've root by uuid for.
