### ISSUE TITLE
3.0-v2 Unable to build sun5i_defconfig

### ISSUE THREAD

**Issue by ghost** [linux-sunxi/linux-sunxi#68]
When I try build defconfig I'm getting this error:
arch/arm/mach-sun5i/core.c:418:16: error: return type is an incomplete type
arch/arm/mach-sun5i/core.c: In function 'sw_get_ic_ver':
arch/arm/mach-sun5i/core.c:425:10: error: 'MAGIC_VER_B' undeclared (first use in this function)
arch/arm/mach-sun5i/core.c:425:10: note: each undeclared identifier is reported only once for each function it appears in
arch/arm/mach-sun5i/core.c:425:3: warning: 'return' with a value, in function returning void [enabled by default]
arch/arm/mach-sun5i/core.c:428:9: error: 'MAGIC_VER_A' undeclared (first use in this function)
arch/arm/mach-sun5i/core.c:428:2: warning: 'return' with a value, in function returning void [enabled by default]
make[1]: **\* [arch/arm/mach-sun5i/core.o] Error 1
make: **\* [arch/arm/mach-sun5i] Error 2

I can find it in system.h L61
But it's commented.
# if 0

enum sw_ic_ver {
    MAGIC_VER_A = 0,
    MAGIC_VER_B,
    MAGIC_VER_C
};

enum sw_ic_ver sw_get_ic_ver(void);
# endif

**Comment by amery** [comment]
this got fixed by 8b11fd40f7dfc6b55b75c1f285d6d92813e7e598. also, please note sun5i support in 3.0-v2 is based on the bits found in Qware's release dating back to December 2012.

we have a work in progress branch (`wip/lichee3-sunxi/import-sun5i`) merging both pieces, the partial code Tsvetan received on the GPL violating SDK and Qware's release. This branch is frozen at 3.0.8, but hopefully the interesting parts will be included in the 3.0-v2 and 3.4 branches soon.
