### ISSUE TITLE
Regression: purple colors when using DVI monitor

### ISSUE THREAD

**Issue by maxnet** [linux-sunxi/linux-sunxi#92]
When connecting an A10 device to a DVI monitor using a HDMI<>DVI adapter  I get an overly purple screen.
Probably the result of YUV instead of RGB color space being used.

Problem does not exist with a Linux kernel I build from github source a month ago (on Sep 21).
But did exist with the original Android image that came with the device.
So apparently this is an issue that has been fixed in the past, but one of the recent video related commits broke it  again.

**Comment by techn** [comment]
Could you test following revision: e3f1324ba6 (video: sun4i: modify csc;) and if problem exists: 9d65b9597e(block: sunxi_nand: accept type 1 partitions too).
Modifications related to this came from Allwinner. And it seems that your stock kernel had modifications already in. I have already workaround in my mind if you can verify that problem is not seen with e3f1324ba6.

**Comment by maxnet** [comment]
e3f1324 does not have the same problem.

(e3f1324 is not perfect either, as it does have a thin purple line to the left of the screen that should not be there: http://postimage.org/image/mhhqed3ut/
But it is not as bad as the newest release where the entire screen is purple: 
http://postimage.org/image/arnp0od8b/ )

**Comment by techn** [comment]
Thanks. I'll send patch for stage when I get back home.

2012/11/1 maxnet notifications@github.com

**Comment by techn** [comment]
I send fix proposal to ML. Please try that :)
https://groups.google.com/forum/?fromgroups=#!topic/linux-sunxi/b-lm8hNbpa4

Fix proposal is just workaround.
This needs to be fixed with better patch after whole disp has been re-formatted.

**Comment by maxnet** [comment]
Applied the workaround, and can confirm it fixes the issue.
